# ===============================
# DATABASE
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/semestr
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# APPLICATION
# ===============================
spring.application.name=semestrWork3

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
spring.jpa.show-sql=true

# ===============================
# FREEMARKER & MVC
# ===============================
spring.freemarker.template-loader-path=classpath:/templates/
spring.freemarker.suffix=.ftl
spring.freemarker.charset=UTF-8
spring.mvc.view.suffix=.ftl

# ===============================
# JWT
# ===============================
jwt.secret=5UqKy/eQOxdM/TeWHPp5cNPvjugsXiKjry5c6diqB6I=
jwt.expiration=86400000

# ===============================
# CUSTOM APP CONFIGURATION
# ===============================
app.security.secret-key=adminShop

app.github.client-id=${CLIENT_ID}
app.github.client-secret=${CLIENT_SECRET}
app.github.client-uri=http://localhost:8080/oauth/github/callback

app.google.api-key=${API_KEY}
##-DSHEET_ID=124132423423 -DAPI_KEY=323532532
app.google.sheets-id=${SHEETS_ID}
# URL ???????
app.google.url=https://docs.google.com/spreadsheets/d/1x1ik3SkXBJBCCloDDZMTPx3SQToGN1clf8e5w5hdv54/edit?usp=sharing

# ===============================
# SPRINGDOC / SWAGGER
# ===============================
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.display-request-duration=true
springdoc.swagger-ui.try-it-out-enabled=true
springdoc.swagger-ui.doc-expansion=none
springdoc.default-produces-media-type=application/json
springdoc.default-consumes-media-type=application/json